from parser.parser import Parser
from interpreter.interpreter import Interpreter

def main():
    source_code = "5 + 10 * (3 - 1 * (2 + 5))"
    parser = Parser(source_code)
    print(parser.tokens)  # Display the tokens generated by the lexer

    parse_tree = parser.parse()
    if parse_tree:
        interpreter = Interpreter(parse_tree)
        result = interpreter.interpret()
        print(result)  # Display the result of the interpretation
        

if __name__ == "__main__":
    main()